# Generated by Django 4.2.16 on 2024-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movil', models.CharField(max_length=12)),
                ('saldo', models.IntegerField()),
                ('datos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plataforma', models.CharField(choices=[('PRE', 'Prepago'), ('POST', 'Postpago')], default='PRE', max_length=4)),
            ],
        ),
    ]
