# Generated by Django 4.2.16 on 2024-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
