# Generated by Django 4.2.16 on 2024-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupos', '0002_alter_cupos_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos',
            name='numero_movil',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
