# Generated by Django 4.2.16 on 2024-09-14 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupos', '0006_alter_cupos_fecha_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos',
            name='fecha_corte',
            field=models.DateField(blank=True, default=datetime.date(2024, 10, 20), null=True),
        ),
    ]
