# Generated by Django 4.2.16 on 2024-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupos', '0007_alter_cupos_fecha_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupos',
            name='fecha_corte',
            field=models.DateField(),
        ),
    ]
