# Generated by Django 4.2.16 on 2024-09-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuarios_options_usuarios_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero_movil',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
