# Generated by Django 4.2.16 on 2024-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuarios_numero_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
