# Generated by Django 4.2.16 on 2024-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cupos', '0002_alter_cupos_saldo'),
        ('Usuarios', '0005_alter_usuarios_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cupos',
            field=models.ManyToManyField(to='Cupos.cupos'),
        ),
    ]
